### PR TITLE
Feat/process compose multi network

### PR DESCRIPTION
**Pull request by tgunnoe**
# Description
This adds preprod and mainnet to the process compose stack, and updates nixpkgs/process-compose to the latest versions. The data has been properly sorted within `.run` by network.

to use the shell, add 
`NIX_SHELL=".#process-compose"`
to your `.envrc.local` file.
and run `direnv reload`

to use one network over the other, run
`partnerchains-stack --namespace preprod`
or to use multiple:
`partnerchains-stack --n preprod -n mainnet -n preview`

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages.
- [ ] New tests are added if needed and existing tests are updated.
- [ ] Relevant logging and metrics added
- [x] CI passes. See note on CI.
- [ ] Any changes are noted in the `changelog.md` for affected crate
- [x] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG Partner Chains developers to do this
for you.

### CODE REVIEW

**Review by LGLO — COMMENTED** [review]
By default it starts both stacks at same time, I don't think it is expected behavior

**Comment by LGLO** [comment]
Please fix PR description:
`bash: sidechains-stack: command not found`

**Comment by tgunnoe** [comment]
@LGLO I fixed that by making a wrapper script that does preview by default, but allows running others or all

**Review by chrispalaskas — COMMENTED** [review]
I see this in the help menu:
  -n, --namespace stringArray   run only specified namespaces (default all)
but default is preview.

**Comment by chrispalaskas** [comment]
Then I try -n doesn't seem to work, only --namespace preview and --namespace preprod work. 
```
partnerchains-stack --namespace both   
+ process-compose --no-server --namespace both
+ set +x
```
But partnerchains-stack -n both  runs only preview and returns after closing:
```
+ process-compose --no-server --namespace preview -n both
+ set +x
```
partnerchains-stack -n preprod Runs both!
+ process-compose --no-server --namespace preview -n preprod
+ set +x

<partnerchains-stack -n preview>,  <partnerchains-stack --namespace preview> and <partnerchains-stack --namespace preprod> work as expected.

**Comment by tgunnoe** [comment]
Ah. the help menu isn't agreeing with the wrapper commands I added.  I could possibly do a patch to process-compose itself to add there commands directly.
also, i got rid of the "both", so now its just --namespace preview --namespace preprod. but good point, -n should work as well. I'll update that and try the combos you did. thanks sir

**Review by chrispalaskas — APPROVED** [review]
Tested all networks, looks good.

**Pull request merged**
